name: pet_buddy
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  permission_handler: ^10.4.3
  firebase_storage: ^11.2.5
  syncfusion_flutter_calendar: ^22.2.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
